config/routes.rb
IcVps::Application.routes.draw do
  ###############################################
  # パートナーページ用リソース
  ###############################################
  # TOP
  root to: "top#index", only: :index
  # deviseを使ったユーザー認証
  devise_for :partners, controllers: {sessions: 'sessions'}
  # VPS管理
  resources :vps_management

  resources :partners do
    resources :private_servers do
      member { put "stop", "start", "reboot" }
    end
  end
  # プライベートサーバー
  resources :private_servers
  # パートナー（アカウントサービス）
  resource :partner do

  end
  # お問い合わせ
  resources :contacts, only: [:index, :show, :new, :create]

  # お知らせ
  resources :notifications, only: [:index, :show]
  # サポートページ
  resource :user_support
  # パートナー用FAQページ
  resources :faqs, only: [:index, :show, :search] do
    collection do
      get "search"
    end
  end
  # パートナー用FAQのカテゴリー別ページ
  resources :faq_categories, only: [:index, :show] do
    resources :faqs, only: [:index, :show]
  end
  # staticページ
  get "/page/:action" => "pages#:action"

  ###############################################
  # アドミンページ用リソース
  ###############################################
  namespace :admin do
    # 管理者トップ
    root to: "top#index"
    # Devise
    devise_for :administrators, controllers: {sessions: 'admin/sessions'}
    # パートナーリソース
    resources :partners do
      collection { get "search" }
      # プライベートサーバー
      resources :private_servers
    end
    # プライベートサーバー
    resources :private_servers
    # アドミンリソース
    resources :administrators do
      collection { get "search" }
    end
    # お知らせリソース
    resources :notifications do
      collection { get "search" }
    end
    # ドメインテンプレート
    resources :domain_templates do
      collection { get "search" }
    end
    # FAQカテゴリー
    resources :faq_categories
    # FAQ
    resources :faqs do
      collection { get "search" }
    end
    # UserSupport
    resource :user_support

    resources :contacts do
      collection { get "search"}
    end
    # ログ管理
    resources :partner_operation_logs, only: [:index]
  end
end

app/models/faq_category.rb
# coding: utf-8
class FaqCategory < ActiveRecord::Base
  has_many :faqs, class_name: "Faq"
  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/admin/faq_categories_controller.rb
# coding: utf-8
class Admin::FaqCategoriesController < Admin::Base
  before_filter :authenticate_admin_administrator!
  # GET /admin/faq_categories
  # GET /admin/faq_categories.json
  # 一覧表示アクション。
  def index
    @admin_faq_categories = FaqCategory.order(:id).
      paginate(page: params[:page], per_page: 5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_faq_categories }
    end
  end

  # GET /admin/faq_categories/1
  # GET /admin/faq_categories/1.json
  def show
    @admin_faq_category = FaqCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_faq_category }
    end
  end

  # GET /admin/faq_categories/new
  # GET /admin/faq_categories/new.json
  def new
    @admin_faq_category = FaqCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_faq_category }
    end
  end

  # GET /admin/faq_categories/1/edit
  def edit
    @admin_faq_category = FaqCategory.find(params[:id])
  end

  # POST /admin/faq_categories
  # POST /admin/faq_categories.json
  def create
    @admin_faq_category = FaqCategory.new(params[:faq_category])

    respond_to do |format|
      if @admin_faq_category.save
        format.html { redirect_to [:admin, @admin_faq_category], notice: 'FAQを追加しました' }
        format.json { render json: @admin_faq_category, status: :created, location: @admin_faq_category }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_faq_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/faq_categories/1
  # PUT /admin/faq_categories/1.json
  def update
    @admin_faq_category = FaqCategory.find(params[:id])

    respond_to do |format|
      if @admin_faq_category.update_attributes(params[:admin_faq_category])
        format.html { redirect_to [:admin, @admin_faq_category], notice: 'FAQを更新しました' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_faq_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/faq_categories/1
  # DELETE /admin/faq_categories/1.json
  def destroy
    @admin_faq_category = FaqCategory.find(params[:id])
    @admin_faq_category.destroy

    respond_to do |format|
      format.html { redirect_to admin_faq_categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/faq_categories_controller.rb
class FaqCategoriesController < ApplicationController
  before_filter :authenticate_partner!
  before_filter :record, only: ['update', 'create', 'destroy']
  def index
    @faq_categories = FaqCategory.order(:id).
      paginate(page: params[:page], per_page: 5)
  end
end

app/helpers/admin/faq_categories_helper.rb
module Admin::FaqCategoriesHelper
end

app/views/admin/faq_categories/_faq_category_list.html.erb
<table>
  <tr>
    <th>名前</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @admin_faq_categories.each do |admin_faq_category| %>
  <tr>
    <td><%= admin_faq_category.name %></td>
    <td><%= link_to '詳細', [:admin, admin_faq_category] %></td>
    <td><%= link_to '編集', edit_admin_faq_category_path(admin_faq_category) %></td>
    <td><%= link_to '削除', admin_faq_category, confirm: '削除しますか?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/admin/faq_categories/_form.html.erb
<%= render "shared/errors", obj: @admin_faq_category %>
<%= form_for([:admin, @admin_faq_category]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/faq_categories/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_faq_category %> |
<%= link_to 'Back', admin_faq_categories_path %>

app/views/admin/faq_categories/index.html.erb
<h1>FAQカテゴリー一覧</h1>
<br />
<%= link_to 'FAQのカテゴリーを追加する', new_admin_faq_category_path %>
<div id="admin_list">
  <% if @admin_faq_categories %>
    <%= render "faq_category_list"%>
    <%= will_paginate @admin_faq_categories %>
  <% else %>
    表示できる管理者情報がありません
  <% end %>
</div>

app/views/admin/faq_categories/new.html.erb
<h1>FAQカテゴリーの追加</h1>
<br />
<%= render 'form' %>

<%= link_to 'Back', admin_faq_categories_path %>

app/views/admin/faq_categories/show.html.erb
<p>
  <b>名前</b>
  <%= @admin_faq_category.name %>
</p>


<%= link_to 'Edit', edit_admin_faq_category_path(@admin_faq_category) %> |
<%= link_to 'Back', admin_faq_categories_path %>