config/routes.rb
IcVps::Application.routes.draw do
  ###############################################
  # パートナーページ用リソース
  ###############################################
  # TOP
  root to: "top#index", only: :index
  # deviseを使ったユーザー認証
  devise_for :partners, controllers: {sessions: 'sessions'}
  # VPS管理
  resources :vps_management

  resources :partners do
    resources :private_servers do
      member { put "stop", "start", "reboot" }
    end
  end
  # プライベートサーバー
  resources :private_servers
  # パートナー（アカウントサービス）
  resource :partner do

  end
  # お問い合わせ
  resources :contacts, only: [:index, :show, :new, :create]

  # お知らせ
  resources :notifications, only: [:index, :show]
  # サポートページ
  resource :user_support
  # パートナー用FAQページ
  resources :faqs, only: [:index, :show, :search] do
    collection do
      get "search"
    end
  end
  # パートナー用FAQのカテゴリー別ページ
  resources :faq_categories, only: [:index, :show] do
    resources :faqs, only: [:index, :show]
  end
  # staticページ
  get "/page/:action" => "pages#:action"

  ###############################################
  # アドミンページ用リソース
  ###############################################
  namespace :admin do
    # 管理者トップ
    root to: "top#index"
    # Devise
    devise_for :administrators, controllers: {sessions: 'admin/sessions'}
    # パートナーリソース
    resources :partners do
      collection { get "search" }
      # プライベートサーバー
      resources :private_servers
    end
    # プライベートサーバー
    resources :private_servers
    # アドミンリソース
    resources :administrators do
      collection { get "search" }
    end
    # お知らせリソース
    resources :notifications do
      collection { get "search" }
    end
    # ドメインテンプレート
    resources :domain_templates do
      collection { get "search" }
    end
    # FAQカテゴリー
    resources :faq_categories
    # FAQ
    resources :faqs do
      collection { get "search" }
    end
    # UserSupport
    resource :user_support

    resources :contacts do
      collection { get "search"}
    end
    # ログ管理
    resources :partner_operation_logs, only: [:index]
  end
end

app/views/shared/_admin_menu_bar.html.erb
<div id="menu">
  <ul>
    <li>
      <%= link_to "TOP", :admin_root %>
    </li>
    <li>
      <%= link_to "パートナーアカウント", :admin_partners %>
    </li>
    <li>
      <%= link_to "ドメインテンプレート", :admin_domain_templates %>
    </li>
    <li>
      <%= link_to "一般サポート関連", :admin_user_support %>
    </li>
    <% if current_admin_administrator %>
      <li>
        <%= link_to "ログアウト", destroy_admin_administrator_session_path, method: :delete,
          confirm: "ログアウトしますか？" %>
      </li>
    <% else %>
      <li>
        <%= link_to "ログイン", new_admin_administrator_session_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% unless obj.errors.empty? %>
  <div id="errors">
    <h2>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </h2>
  </div>
<% end %>

app/views/shared/_login_form.html.erb
<h3>ログイン</h3>
<% if flash.alert %>
  <p class="alert"><%= flash.alert %></p>
<% end %>
<%= form_tag :admin_session do %>
  <table id="login_form">
    <tr>
      <td align="left">ID</td>
      <td>
        <%= text_field_tag "email", "", style: "width: 120px" %>
      </td>
    </tr>
    <tr>
      <td align="left">Password</td>
      <td>
        <%= password_field_tag "password", "", style: "width: 120px" %>
      </td>
    </tr>
    <tr>
      <td colspan="2" align="center">
        <%= submit_tag "ログイン" %>
      </td>
    </tr>
  </table>
  <%= hidden_field_tag "from", request.path %>
<% end %>

app/views/shared/_menu_bar.html.erb
<div id="menu">
  <ul>
    <li>
      <%= link_to "IC-VPS トップ", :root %>
    </li>
    <li>
      <%= link_to "サーバー管理", :vps_management_index %>
    </li>
    <li>
      <%= link_to "アカウントサービス", '/partner' %>
    </li>
    <li>
      <%= link_to 'お問い合わせフォーム', :new_contact %>
    </li>
    <% if current_partner %>
      <li>
        <%= link_to "ログアウト", destroy_partner_session_path,
            method: :delete, confirm: "ログアウトしますか？" %>
      </li>
    <% else %>
      <li>
        <%= link_to "ログイン", new_partner_session_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_partner_side_menu.html.erb
<div id="sub">
  <div class="section">
    <h3>サポート</h3>
    <ul>
      <li>
        <%= link_to 'サポートTOP', :user_support %>
      </li>
      <li>
        <%= link_to 'お問い合わせ一覧', :contacts %>
      </li>
      <li>
        <%= link_to 'お問い合わせフォーム', :new_contact %>
      </li>
      <li>
        <%= link_to 'よくあるご質問', :faqs %>
      </li>
    </ul>
    <!-- /.section -->
  </div>
  <div class="section">
    <h3>会社概要</h3>
    <ul>
      <li>
        <%= link_to "会社概要", 'http://www.ic-net.or.jp/company/infomation.html', target: "_blank" %>
      </li>
    </ul>
    <!-- /.section -->
  </div>
  <div class="section">
    <h3>個人情報について</h3>
    <ul>
      <li>
        <%= link_to '個人情報保護方針', '/page/privasy_policy' %>
      </li>
      <li>
        <%= link_to '開示対象個人情報について', '/page/disclosure_personal_info' %>
      </li>
    </ul>
    <!-- /.section -->
  </div>
  <!-- /#sub -->
</div>

app/views/shared/_side_menu.html.erb
<div id="sub">
  <div class="section">
    <h3>カテゴリ</h3>
    <ul>
      <li>
        <a href="index.html">サブメニュー1</a>
      </li>
      <li>
        <a href="index.html">サブメニュー2</a>
      </li>
      <li>
        <a href="index.html">サブメニュー3</a>
      </li>
    </ul>
    <!-- /.section -->
  </div>
  <div class="section">
    <h3>カテゴリ</h3>
    <ul>
      <li>
        <a href="index.html">サブメニュー4</a>
      </li>
      <li>
        <a href="index.html">サブメニュー5</a>
      </li>
      <li>
        <a href="index.html">サブメニュー6</a>
      </li>
    </ul>
    <!-- /.section -->
  </div>
  <!-- /#sub -->
</div>

app/views/shared/_topic_path.html.erb
<div id="topicPath">
  <%= render_crumbs %>
</div>